version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./laravel:/app
    ports:
      - "8000:8000" #
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./laravel:/app
      - ./nginx-config:/etc/nginx/conf.d # Mount a directory for custom Nginx configuration
    depends_on:
      - app
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "database"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data:
