version: '3'
services:
  app:
    image: composer:latest
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: create-project --prefer-dist laravel/laravel .
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./laravel:/app
    depends_on:
      - app