version: '3'
services:
  app:
    image: composer:latest
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000 # Update the host and port as needed

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./laravel:/app
      - ./nginx-config:/etc/nginx/conf.d # Mount a directory for custom Nginx configuration
    depends_on:
      - app
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'database'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306