version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-in-docker-new-app-1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000" #
  web:
    image: nginx:alpine
    container_name: laravel-in-docker-new-web-1
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx-config:/etc/nginx/conf.d # Mount a directory for custom Nginx configuration
    depends_on:
      - app
  db:
    image: mysql:8.1
    container_name: laravel-in-docker-new-db-1
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data:
